### ISSUE TITLE
Cannot alias Shellvar, resource already declared

### ISSUE THREAD

**Issue by Hufschmidt** [voxpupuli/puppet-augeasproviders_shellvar#31]
The following code works fine with version **2.2.2**, but fails with catalog-compilation error on version **2.2.3**.

```puppet
  exec { 'update grub':
    command     => '/usr/sbin/update-grub',
    refreshonly => true,
  }

  shellvar { 'default to noop elevator':
    ensure       => present,
    target       => '/etc/default/grub',
    variable     => 'GRUB_CMDLINE_LINUX',
    value        => 'elevator=noop',
    array_append => true,
    notify       => Exec['update grub'],
  }

  if ($::kernel == 'Linux' and $::virtual == 'kvm') {
    shellvar { 'configure serial console':
      ensure       => present,
      target       => '/etc/default/grub',
      variable     => 'GRUB_CMDLINE_LINUX',
      value        => 'console=ttyS0,115200n8',
      array_append => true,
      notify       => Exec['update grub'],
    }
  }
```

Error message:

> Error: Could not retrieve catalog from remote server: 
> Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, 
> Cannot alias Shellvar[configure serial console] to ["/etc/default/grub", "GRUB_CMDLINE_LINUX"] at 
> [[second resource definition]];
> resource ["Shellvar", "/etc/default/grub", "GRUB_CMDLINE_LINUX"] already declared at 
> [[first resource definition]] at 
> [[second resource definition]] 
> on node [[detracted]]
> Warning: Not using cache on failed catalog

**Comment by Hufschmidt** [comment]
Maybe [this](https://tickets.puppetlabs.com/browse/PUP-1073) helps. It seems like (at lest with `array_append => true`) the value needs to be part of the unique resource name...

**Comment by raphink** [comment]
I'm not really sure to understand why switching the `title_patterns` method broke this.

In any case:

* I'm pretty sure `array_append` has nothing to do with this, it's just the fact of having two resources with the same `target`/`variable` combination
* Properties cannot be used as namevars, as namevars need to be parameters since they identify the resource as primary keys.

Mainly, I can't reproduce this either Puppet 4.10 or 5.5. Which version of Puppet are you using?

**Comment by Hufschmidt** [comment]
> * I'm pretty sure `array_append` has nothing to do with this, it's just the fact of having two resources with the same `target`/`variable` combination

Oh ok, thanks you for clearing this confusion. I thought this is the intended use-case, similar to _puppetlabs-inifile_ `subsetting` parameter.

> Mainly, I can't reproduce this either on Puppet 4.10 or 5.5. Which version of Puppet are you using?

This happened with Puppet 4.10. 

Since I was able to solve this using _hercules-team/augeasproviders_grub_ instead and given your above explanation I think we can close this issue as it seems to be the intended behavior.

**Comment by kenyon** [comment]
Running into this exact same problem now with Puppet 6.27.0 and augeasproviders_shellvar v5.0.0. 😒 I'm even trying to set the same variable in the same file, `GRUB_CMDLINE_LINUX` in `/etc/default/grub`, because I gave up on augeasproviders_grub due to https://github.com/voxpupuli/puppet-augeasproviders_grub/issues/74 (it also has the same alias problem too though, if you want to set the same parameters for multiple bootmodes as you need to do to support both RHEL and Debian and need to modify `GRUB_CMDLINE_LINUX_DEFAULT` and `GRUB_CMDLINE_LINUX`).

It's starting to look like I might need to use `file_line` or just manage the whole `/etc/default/grub` file.

**Comment by kenyon** [comment]
Silly workaround, but it seems to work fine: add extra slashes to the `target` path.

```puppet
shellvar { 'wanted kernel parameters':
  ensure       => present,
  variable     => 'GRUB_CMDLINE_LINUX',
  target       => '/etc/default//grub',
  value        => [
    'audit=1',
  ],
  array_append => true,
  notify       => Exec['update-grub'],
}

shellvar { 'unwanted kernel parameters':
  ensure       => absent,
  variable     => 'GRUB_CMDLINE_LINUX',
  target       => '/etc/default/grub',
  value        => [
    'nomodeset',
    'quiet',
    'splash',
  ],
  array_append => true,
  notify       => Exec['update-grub'],
}
```

**Comment by P6wG7** [comment]
Got the same issue with puppet 8.5.1 and this very small patch fixed on my side:
```diff
diff --git a/lib/puppet/type/shellvar.rb b/lib/puppet/type/shellvar.rb
index 70c99c6..97378ae 100644
--- a/lib/puppet/type/shellvar.rb
+++ b/lib/puppet/type/shellvar.rb
@@ -55,6 +55,7 @@ Puppet::Type.newtype(:shellvar) do
 
   newparam(:name) do
     desc 'The default namevar'
+    isnamevar
   end
 
   newparam(:variable) do
```

This is added in that PR: https://github.com/voxpupuli/puppet-augeasproviders_shellvar/pull/61

**Comment by kenyon** [comment]
Fixed by #61.
